import { useParams } from 'next/navigation';
import React, { useCallback, useEffect, useState } from 'react';

import { CreateRoom } from '@/lib/API/room/mutations';
import { GetRoomsByTemplateId } from '@/lib/API/room/queries';
import { Room } from '@/lib/types/room';

import { Modal } from '@/components/ui/Modal';

import ChatRoomPage from './chat';
import RoomCreateForm from './RoomCreateForm';

interface TemplateRowProps {
  name: string;
  constraints: string[];
  templateId: string;
  onDelete: () => void;
  onUpdate: (updatedData: { name: string; constraints: string[] }) => void;
}

const TemplateRow: React.FC<TemplateRowProps> = ({
  name,
  constraints,
  templateId,
  onDelete,
  onUpdate,
}) => {
  const { courseId } = useParams<{ courseId: string }>(); // Extract courseId using useParams
  const [isExpanded, setIsExpanded] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editName, setEditName] = useState(name);
  const [editConstraints, setEditConstraints] = useState(
    constraints.join(', ')
  );
  const [isRoomModalOpen, setIsRoomModalOpen] = useState(false); // Modal for room creation
  const [rooms, setRooms] = useState<Room[]>([]); // Add state to hold rooms
  const [isChatModalOpen, setIsChatModalOpen] = useState(false); // Modal for chat room
  const [selectedRoom, setSelectedRoom] = useState<Room | null>(null); // Store the selected room object

  const toggleExpand = () => {
    setIsExpanded((prev) => !prev);
    setIsEditing(false);
  };

  const toggleEdit = (e: React.MouseEvent) => {
    e.stopPropagation();
    setIsEditing((prev) => !prev);
  };

  const handleUpdate = () => {
    const updatedConstraints = editConstraints.split(',').map((c) => c.trim());
    onUpdate({ name: editName, constraints: updatedConstraints });
    setIsEditing(false);
  };

  const handleCreateRoom = async (roomData: {
    roomName: string;
    description: string;
  }) => {
    const autoGeneratedCode = Math.random()
      .toString(36)
      .substr(2, 6)
      .toUpperCase();
    try {
      await CreateRoom({
        courseId,
        name: roomData.roomName,
        description: roomData.description,
        code: autoGeneratedCode,
        template: templateId,
      });
      fetchRooms(courseId, templateId);
    } finally {
      setIsRoomModalOpen(false);
    }
  };

  const fetchRooms = useCallback(
    async (courseId: string, templateIdString: string) => {
      if (!templateIdString) return;
      try {
        const rooms = await GetRoomsByTemplateId(courseId, templateIdString);
        setRooms(rooms || []);
      } catch {
        // Handle errors here if necessary
      }
    },
    []
  );

  useEffect(() => {
    if (isExpanded) {
      fetchRooms(courseId, templateId);
    }
  }, [isExpanded, courseId, templateId, fetchRooms]);

  // Handler for clicking on a room, which opens the chat modal
  const handleRoomClick = (room: Room) => {
    setSelectedRoom(room);
    setIsChatModalOpen(true); // Open chat modal when a room is clicked
  };

  return (
    <>
      <tr
        onClick={toggleExpand}
        className={`cursor-pointer transition-colors duration-300 ${
          isExpanded ? 'bg-gray-200' : 'hover:bg-gray-100'
        }`}
      >
        <td className='border-b py-2 px-4'>
          {isEditing ? (
            <input
              type='text'
              value={editName}
              onChange={(e) => setEditName(e.target.value)}
              className='border p-1'
            />
          ) : (
            name
          )}
        </td>

        <td className='border-b py-2 px-4 flex space-x-2'>
          {isEditing ? (
            <button
              onClick={(e) => {
                e.stopPropagation();
                handleUpdate();
              }}
              className='bg-blue-600 text-white px-2 py-1 rounded'
            >
              Save
            </button>
          ) : (
            <button
              onClick={toggleEdit}
              className='text-blue-600 px-2 py-1 rounded'
            >
              Edit
            </button>
          )}

          <button
            onClick={(e) => {
              e.stopPropagation();
              onDelete();
            }}
            className='text-red-600 px-2 py-1 rounded'
          >
            Delete
          </button>

          <button
            onClick={(e) => {
              e.stopPropagation();
              setIsRoomModalOpen(true);
            }}
            className='bg-green-600 text-white px-2 py-1 rounded'
          >
            Create Room
          </button>
        </td>
      </tr>

      {isExpanded && (
        <tr>
          <td colSpan={2} className='border-b py-2 px-4'>
            {isEditing ? (
              <div className='mb-2'>
                <label className='font-semibold'>Constraints:</label>
                <textarea
                  value={editConstraints}
                  onChange={(e) => setEditConstraints(e.target.value)}
                  className='border p-1 w-full'
                />
              </div>
            ) : (
              <>
                <ul className='list-disc pl-5'>
                  {constraints.map((constraint, index) => (
                    <li key={index}>{constraint}</li>
                  ))}
                </ul>

                {/* Display the rooms when expanded */}
                <div className='mt-4'>
                  <h3 className='font-semibold'>Rooms</h3>
                  {rooms.length === 0 ? (
                    <p>No rooms available for this template.</p>
                  ) : (
                    <ul className='list-disc pl-5'>
                      {rooms.map((room) => (
                        <li
                          key={room.id}
                          className='cursor-pointer text-blue-600 hover:underline'
                          onClick={() => handleRoomClick(room)} // Pass the entire room object when clicked
                        >
                          {room.name} - {room.description}
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              </>
            )}
          </td>
        </tr>
      )}

      {/* Room creation modal */}
      {isRoomModalOpen && (
        <Modal
          title='Create New Room'
          onClose={() => setIsRoomModalOpen(false)}
        >
          <RoomCreateForm onCreateRoom={handleCreateRoom} />
        </Modal>
      )}

      {/* Chat room modal */}
      {isChatModalOpen && selectedRoom && (
        <Modal
          title={`Chat Room - ${selectedRoom.name}`} // Display room name in the modal title
          onClose={() => setIsChatModalOpen(false)} // Close the modal on user action
        >
          <ChatRoomPage
            roomName={selectedRoom.name}
            roomDescription={selectedRoom.description}
            courseId={courseId}
            templateId={selectedRoom.templateId}
          />
        </Modal>
      )}
    </>
  );
};

export default TemplateRow;
