services:
  client:
    build:
      context: ./packages/client
      dockerfile: ./Dockerfile.development
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - frontend
    depends_on:
      - server

  server:
    build:
      context: ./packages/server
      dockerfile: ./Dockerfile.development
    environment:
      - NODE_ENV=development
    ports:
      - "4999:5000"
    networks:
      - frontend
      - backend
    depends_on:
      - mongo

  mongo:
    image: mongodb/mongodb-atlas-local
    env_file:
      - .env.db.development
    ports:
      - "27018:27017"
    networks:
      - backend
    volumes:
      - data:/data/db
      - config:/data/configdb

volumes:
  data:
  config:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
