version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client # Build only the client stage
    image: ai-pal-client
    ports:
      - "3000:3000" # Client runs on port 3000
    networks:
      - app-network
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server # Build only the server stage
    image: ai-pal-server
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - "5000:5000" # Server runs on port 5000
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
