/* eslint-disable no-console */
import toast from 'react-hot-toast';

import { showLogger } from '@/constant/env';

/**
 * A logger function that will only logs on development
 * @param object - The object to log
 * @param comment - Autogenerated with `lg` snippet
 */
export default function logger(object: unknown, comment?: string): void {
  // Determine if this is an error log
  const isError = object instanceof Error;

  if (typeof window !== 'undefined') {
    if (isError) {
      // Always show toast.error for errors, with fallback message
      toast.error(comment || 'Something went wrong!');
    } else if (comment) {
      // Only show toast.success if there's a comment
      toast.success(comment);
    }
  }

  if (!showLogger) return;

  console.log(
    '%c ============== INFO LOG \n',
    'color: #22D3EE',
    `${typeof window !== 'undefined' && window?.location.pathname}\n`,
    `=== ${comment ?? ''}\n`,
    object
  );
}
