name: Build and Push Development Images to GitHub Container Registry

on:
  push:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      packages: write
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Convert repository name to lowercase
      - name: Lowercase github.repository
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # Step 4: Build and push Server image
      - name: Build and push Server image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/server
          file: ./packages/server/Dockerfile.development
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/server-development:latest

      # Step 5: Build and push Client image
      - name: Build and push Client image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/client
          file: ./packages/client/Dockerfile.development
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/client-development:latest

      - name: Print success message
        run: echo "Server and client images have been built and pushed to registry!"