name: Enforce Source Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from development
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          if [ "$SOURCE_BRANCH" != "development" ]; then
            echo "Error: Pull requests to main must originate from the 'development' branch."
            exit 1
          fi
